import { Link } from 'react-router-dom';

export function Footer() {
  return (
    <>
      <section className="max-w-7xl mx-auto px-8 py-16 border-t border-outline-variant/20">
        <div className="flex flex-col md:flex-row items-center justify-between mb-12 gap-6">
          <div>
            <h2 className="font-headline-xl text-headline-xl mb-4">Next-Gen AI Trading Assistant</h2>
            <p className="text-on-surface-variant text-body-lg max-w-2xl">Harness the power of machine learning to navigate complex markets with confidence.</p>
          </div>
          <div className="flex items-center gap-3 bg-surface-container-high p-4 rounded-2xl border border-primary/20">
            <span className="material-symbols-outlined text-primary animate-pulse">psychology</span>
            <span className="text-sm font-medium">AI Engine: Active</span>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="p-8 border-l border-primary-container bg-surface-container-low hover:bg-surface-container transition-colors group cursor-default">
            <span className="material-symbols-outlined text-primary text-3xl mb-4">insights</span>
            <h4 className="font-headline-md text-headline-md mb-2 group-hover:text-primary transition-colors">Predictive Signals</h4>
            <p className="text-outline text-sm leading-relaxed">Get real-time entry and exit signals generated by our proprietary neural network trained on decades of market data.</p>
          </div>
          <div className="p-8 border-l border-primary-container bg-surface-container-low hover:bg-surface-container transition-colors group cursor-default">
            <span className="material-symbols-outlined text-primary text-3xl mb-4">query_stats</span>
            <h4 className="font-headline-md text-headline-md mb-2 group-hover:text-primary transition-colors">Automated Analysis</h4>
            <p className="text-outline text-sm leading-relaxed">Our AI scans thousands of charts simultaneously to identify patterns and anomalies that humans might miss.</p>
          </div>
          <div className="p-8 border-l border-primary-container bg-surface-container-low hover:bg-surface-container transition-colors group cursor-default">
            <span className="material-symbols-outlined text-primary text-3xl mb-4">support_agent</span>
            <h4 className="font-headline-md text-headline-md mb-2 group-hover:text-primary transition-colors">24/7 Smart Support</h4>
            <p className="text-outline text-sm leading-relaxed">Instant answers to technical questions and personalized portfolio summaries, available whenever you need them.</p>
          </div>
        </div>
      </section>

      <footer className="bg-surface-container-lowest border-t border-surface-variant py-12">
        <div className="max-w-7xl mx-auto px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-12">
          <div className="md:col-span-1">
            <span className="text-xl font-black tracking-tighter text-white uppercase mb-6 block">
              <div className="flex items-center gap-2 mb-4">
                <img src="/logo.png" alt="Investify Logo" className="h-8 w-8 object-contain rounded-md" />
                <span className="text-xl font-bold tracking-tight text-white uppercase">Investify</span>
              </div>
            </span>
            <p className="text-xs text-outline leading-relaxed">
              Empowering individual investors with the tools once reserved for Wall Street institutions.
            </p>
          </div>
          <div>
            <h5 className="text-xs font-bold text-on-surface uppercase tracking-widest mb-6">Platforms</h5>
            <ul className="space-y-3">
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">Web Terminal</Link></li>
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">Desktop App</Link></li>
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">Mobile iOS</Link></li>
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">Investify Academy</Link></li>
            </ul>
          </div>
          <div>
            <h5 className="text-xs font-bold text-on-surface uppercase tracking-widest mb-6">Resources</h5>
            <ul className="space-y-3">
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">Help Center</Link></li>
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">API Documentation</Link></li>
              <li><Link to="/" className="text-xs text-outline hover:text-primary transition-colors">Risk Disclosure</Link></li>
            </ul>
          </div>
          <div>
            <h5 className="text-xs font-bold text-on-surface uppercase tracking-widest mb-6">Connect</h5>
            <div className="flex gap-4">
              <a className="w-8 h-8 rounded-full bg-surface-container-low border border-surface-variant flex items-center justify-center text-outline hover:text-white hover:border-outline transition-all" href="#">
                <span className="material-symbols-outlined text-sm">public</span>
              </a>
              <a className="w-8 h-8 rounded-full bg-surface-container-low border border-surface-variant flex items-center justify-center text-outline hover:text-white hover:border-outline transition-all" href="#">
                <span className="material-symbols-outlined text-sm">alternate_email</span>
              </a>
              <a className="w-8 h-8 rounded-full bg-surface-container-low border border-surface-variant flex items-center justify-center text-outline hover:text-white hover:border-outline transition-all" href="#">
                <span className="material-symbols-outlined text-sm">chat_bubble</span>
              </a>
            </div>
          </div>
        </div>
        <div className="pt-8 border-t border-surface-variant flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="font-sans text-[11px] uppercase tracking-widest text-outline">© 2024 Investify Financial Terminal. Real-time data delayed by 15 mins unless subscribed.</p>
          <div className="flex gap-6">
            <Link to="/" className="font-sans text-[11px] uppercase tracking-widest text-outline hover:text-on-surface-variant transition-colors">Privacy Policy</Link>
            <Link to="/" className="font-sans text-[11px] uppercase tracking-widest text-outline hover:text-on-surface-variant transition-colors">Terms of Service</Link>
          </div>
        </div>
        </div>
      </footer>
    </>
  );
}
